name=MY9221LedBar
version=0.0.0
author=mumanchu
maintainer=mumanchu <info@muman.ch>
sentence=Optimized Code for Grove LED Bar v2.0 with MY9221 Controller
paragraph=**PRELIMINARY**
category=Display
includes=MY9221LedBar.h
url=https://github.com/mumanchu/MY9221LedBar
architectures=*
depends=OptimizedGPIO
